### ISSUE TITLE
How should I extract resource block data

### ISSUE THREAD

**Issue by xxxxxy211** [xinuvic/Simulators-for-SPS#2]
I already know that the vehicle selects the resource block to transmit the message through the SPS algorithm. I want to know how to save the results of resource selection in time series, such as storing the resource block usage results (conflict-free use, free, etc.) in a two-dimensional array. This is very important to me, and I hope to export the data for this Offline learning of machine learning algorithms, looking forward to your reply!

**Comment by xinuvic** [comment]
> I already know that the vehicle selects the resource block to transmit the message through the SPS algorithm. I want to know how to save the results of resource selection in time series, such as storing the resource block usage results (conflict-free use, free, etc.) in a two-dimensional array. This is very important to me, and I hope to export the data for this Offline learning of machine learning algorithms, looking forward to your reply!

Hi Xinyu,

Thank you for your thought-provoking question. It is very interesting to save results of resource selection for training. 

In the event that vehicles autonomously sense and access the channel, a challenge arises in terms of detecting conflicts without the exchange of Acknowledgments (Ack) or Negative Acknowledgments (NAck) within a broadcasting scenario. However, vehicles get to know resource usage upon receiving the SCIs from others. Such information can be saved for analysis. 

From my perspective, a practical approach to storing this information involves maintaining an array, determining the time duration, and updating the array periodically by removing outdated data and adding the most recent information. The channels are subdivided into several sub-channels, and time is divided into sub-frames. When focusing on a periodic beacon broadcasting scenario, you can observe the resource selection results within each transmission interval, such as 20 milliseconds. Suppose that the number of sub-channels is $n$, then we can observe $20n$ resources per interval. If your considered $m$ intervals of information, then the array could be $m\times20n$.

If you could share the specific learning objectives and the problem you aim to address, I may be able to provide more tailored advice.

Best regards,
Xin

**Comment by xxxxxy211** [comment]
Hello, Xin,

Thank you for your reply. It was very helpful. I realized that this is not a simple problem, for example, the real situation of channel resource usage should be an unfixed value, for example, for vehicles in different areas at the same time, channel resource usage should be different, which is related to the interference between vehicles. My initial idea is to use the machine learning method to use the data of the perception window (incomplete resource usage due to half-duplex and other reasons) as input to get the optimal resource selection in the selection window. This is more of an end-to-end approach to resource allocation rather than layers of filtering through SPS. Maybe we can exchange opinions in Chinese. Haha.

With best wishes，
Xinyu

**Comment by xinuvic** [comment]
Hi Xinyu,

Thank you for your message! I have been busy in the last few weeks and just saw your message. Sorry for the late reply.

> I realized that this is not a simple problem, for example, the real situation of channel resource usage should be an unfixed value, for example, for vehicles in different areas at the same time, channel resource usage should be different, which is related to the interference between vehicles.

Yes, that's true. The system is highly dynamic, given the vehicle mobility and users' random access behaviors.

> My initial idea is to use the machine learning method to use the data of the perception window (incomplete resource usage due to half-duplex and other reasons) as input to get the optimal resource selection in the selection window. This is more of an end-to-end approach to resource allocation rather than layers of filtering through SPS.

Sounds interesting! I believe this is worth a try. Also, I am curious about how long it takes to obtain the optimal policy, i.e., the convergence performance.

> Maybe we can exchange opinions in Chinese. Haha.

Of course, feel free to send me an email so that we can exchange WeChat or something. My email address is xin.uvic@gmail.com. Looking forward to hearing from you!

Best regards,
Xin

**Comment by xxxxxy211** [comment]
Ok, I'll contact you after I organize my own information.

Thank you for your reply
xinyu
